plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id "com.modrinth.minotaur" version "2.+"
}

repositories {
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }
}

loom {
	splitEnvironmentSourceSets()
	
	mods {
		"just-like-blasts" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
	//TODO also add that in fabric.mod.json on uncommenting it
	accessWidenerPath = file("src/main/resources/just-like-blasts.accesswidener")
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	//implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
	def version = project.version+"-mc"+project.minecraft_version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	repositories {
	}
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN") 
    projectId = "${project.archives_base_name}" 
    //versionNumber = "${project.mod_version}"
    versionType = "alpha" // alpha / beta / release
    uploadFile = jar 
    gameVersions = ["${project.minecraft_version}"]
    //loaders = ["fabric"] 
    dependencies { 
        
    }
}
